### PR TITLE
Use fswatch to watch file changes

### PR DESCRIPTION
**Pull request by mre**
Please test on Linux

### CODE REVIEW

**Review by woolfg — COMMENTED** [review]
After install fswatch it worked partially. I see the output of the changed content, even without a change by just opening the file. But I get those error message in between:

```
====================
sed: can't read /home/woolf/projects/OpenPodcast/api/db_schema/queries/v1/applePodcastFollowers.sql
/home/woolf/projects/OpenPodcast/api/db_schema/queries/v1/applePodcastFollowers.sql
/home/woolf/projects/OpenPodcast/api/db_schema/queries/v1/applePodcastFollowers.sql: No such file or directory
Modified File: /home/woolf/projects/OpenPodcast/api/db_schema/queries/v1/applePodcastFollowers.sql
/home/woolf/projects/OpenPodcast/api/db_schema/queries/v1/applePodcastFollowers.sql
/home/woolf/projects/OpenPodcast/api/db_schema/queries/v1/applePodcastFollowers.sql
====================

====================
sed: can't read /home/woolf/projects/OpenPodcast/api/db_schema/queries/v1
/home/woolf/projects/OpenPodcast/api/db_schema/queries/v1: No such file or directory
Modified File: /home/woolf/projects/OpenPodcast/api/db_schema/queries/v1
/home/woolf/projects/OpenPodcast/api/db_schema/queries/v1
====================
```

**Comment by mre** [comment]
Might be a case of
https://stackoverflow.com/questions/43171648/sed-gives-sed-cant-read-no-such-file-or-directory

**Comment by mre** [comment]
Might be a case of
https://stackoverflow.com/questions/43171648/sed-gives-sed-cant-read-no-such-file-or-directory

**Comment by mre** [comment]
Don't think that's needed anymore.

**Pull request closed without merging**
